version: 2.1
orbs:
  node: circleci/node@3.0.0
  slack: circleci/slack@3.4.2
  twilio: circleci/twilio@0.0.1
jobs:
  build-test-and-notify:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run: npm test
      - slack/notify:
          color: '#42e2f4'
          mentions: 'yemiwebby,'
          message: A custom message to notify the channel about the latest build
      - slack/status:
          fail_only: true
          mentions: 'yemiwebby'
      - twilio/sendsms:
          body: Send SMS to twilio
      - twilio/alert:
          body: Send SMS for error
workflows:
  build-and-notify:
    jobs:
      - build-test-and-notify
